$router_netsetup = <<ROUTER_NETSETUP
ifconfig eth1 up
ifconfig eth1 10.12.0.1
ifconfig eth2 up
ifconfig eth2 10.13.0.1
ROUTER_NETSETUP

Vagrant.configure("2") do |config|
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.synced_folder "./scripts", "/scripts"

   config.vm.define :probe do |probe|
    probe.vm.box = "precise32"
    probe.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--nic2", "intnet"]
      vb.customize ["modifyvm", :id, "--intnet2", "probe"]
    end
    probe.vm.provision :shell, :inline => "/scripts/networksettings.sh 10.12.0.10 10.12.0.1 8.8.8.8" 
    probe.vm.provision :shell, :inline => "/scripts/changehostname.sh probe"
  end

  config.vm.define :backend do |backend|
    backend.vm.box = "precise32"
    backend.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--nic2", "intnet"]
      vb.customize ["modifyvm", :id, "--intnet2", "backend"]
    end
    backend.vm.provision :shell, :inline => "/scripts/networksettings.sh 10.13.0.10 10.13.0.1 8.8.8.8" 
    backend.vm.provision :shell, :inline => "/scripts/changehostname.sh backend"
  end
  
  config.vm.define :router do |router|
    router.vm.box = "precise32"
    router.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--nic2", "intnet"]
      vb.customize ["modifyvm", :id, "--intnet2", "probe"]
    
      vb.customize ["modifyvm", :id, "--nic3", "intnet"]
      vb.customize ["modifyvm", :id, "--intnet3", "backend"]
    end

    ## add iptables rules
    router.vm.provision :shell, :inline => $router_netsetup
    router.vm.provision :shell, :inline => "/scripts/router_iptables.sh"
  end
end
