Vagrant.configure("2") do |config|
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.synced_folder "./scripts", "/scripts"
  config.vm.define :probe do |probe|
    probe.vm.box = "precise32"
    probe.vm.network :private_network, ip: "10.12.0.10"
    probe.vm.provision :shell, :inline => "/scripts/networksettings.sh 10.12.0.1 8.8.8.8"
    probe.vm.provision :shell, :inline => "/scripts/changehostname.sh probe"
  end

  config.vm.define :backend do |backend|
    backend.vm.box = "precise32"
    backend.vm.network :private_network, ip: "10.13.0.10"
    backend.vm.provision :shell, :inline => "/scripts/networksettings.sh 10.13.0.1 8.8.8.8"
    backend.vm.provision :shell, :inline => "/scripts/changehostname.sh backend"
  end
  
  config.vm.define :router do |router|
    router.vm.box = "precise32"
    router.vm.network :private_network, ip: "10.12.0.1"
    router.vm.network :private_network, ip: "10.13.0.1"

    ## add iptables rules
    router.vm.provision :shell, :inline => "/scripts/router_iptables.sh"
    router.vm.provision :shell, :inline => "/scripts/changehostname.sh router"
  end
end
